// Write a C++ program to display. Hello World: output string

#include <iostream.h> // Include the standard input/output stream library
#include <conio.h> // Include the console input/output library

void main()  // The function does not return any value
{
	clrscr(); // Clear the console screen
    cout << "Hello World"; // Output "Hello World" to the console
    getch(); // Wait for a keypress
}